#
# This file is part of Encom.
# 
# Encom is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Encom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser Public License for more details.
#
# You should have received a copy of the GNU Lesser Public License
# along with Encom.  If not, see <http://www.gnu.org/licenses/>.
#
# ==========================================
# 		  DATABASE CONFIGURATIONS
# ==========================================

# This class represents database driver class that will be used while connecting to database
database.driver = com.mysql.cj.jdbc.Driver

# This is database url.
database.url = jdbc:mysql://localhost:3306/al_server_gs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC

# Database user
database.user = root

# Database password
# NOTE: Change this! Root password is not safe!
database.password = aion58

database.maxconnections = 20
database.hikari.maxLifetime = 600000
database.hikari.connectionTestQuery = SELECT 1

# Script context that will be loaded by database factory, it should implement DAO instances
database.scriptcontext.descriptor = ./data/scripts/system/database.xml